os: linux
language: python

sudo: false
python:
 - "3.3"
 - "3.4"
 - "3.5"
 - "3.6"
 - "3.7"
 - "3.8"
 - "pypy"

install:
 - "pip install -r requirements.txt"
 - "pip install ."

script:
  - bash -c echo "Tests must go here"

before_deploy:
  - pyinstaller --onefile --paths kb/ kb/__main__.py

deploy:
  provider: releases
  api_key: $RELEASE_TOKEN
  file_glob: true
  file: dist/*
  skip_cleanup: true
  draft: true
