#
# kbAPI server DOCKER compose file
# 
# :Copyright: © 2020, alshapton.
# :License: GPLv3 (see /LICENSE).
# 

version: '3.7'

services:
  kb:
    build:
      context: ./
      dockerfile: ./docker/api/dockerfile
    volumes:
      - ./docker/data:/data
    tty: true
    ports: 
      - 5000:5000
